package zello

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"strings"
	"testing"
	"time"
)

// Signing the logon token.
//
// **Every key here is generated by the test.** No operator's key appears in
// this repository, and a test that needed one would be a test that could not
// run on anybody else's machine.

// throwawayKey returns a fresh RSA key and its PEM in both common encodings.
func throwawayKey(t *testing.T, bits int) (*rsa.PrivateKey, string, string) {
	t.Helper()
	key, err := rsa.GenerateKey(rand.Reader, bits)
	if err != nil {
		t.Fatalf("generating a key: %v", err)
	}

	pkcs8, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		t.Fatalf("marshalling PKCS#8: %v", err)
	}
	eight := string(pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: pkcs8}))
	one := string(pem.EncodeToMemory(&pem.Block{
		Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key),
	}))
	return key, eight, one
}

const testIssuer = "WkM6dGVzdDox.someSignatureBytes"

// TestATokenVerifiesAgainstThePublicKey is the only check that matters: Zello
// will verify the signature, so the test must too.
//
// **Not a comparison against a stored string.** A golden token would pass for
// any consistent mistake and would need a fixed clock and a fixed key; a
// verification proves the thing Zello actually does.
func TestATokenVerifiesAgainstThePublicKey(t *testing.T) {
	key, pkcs8, _ := throwawayKey(t, MinimumKeyBits)

	fixed := time.Date(2026, 9, 15, 12, 0, 0, 0, time.UTC)
	signer, err := NewSigner(SignerOptions{
		Issuer:        testIssuer,
		PrivateKeyPEM: pkcs8,
		Now:           func() time.Time { return fixed },
	})
	if err != nil {
		t.Fatalf("building a signer: %v", err)
	}

	token, err := signer.Token()
	if err != nil {
		t.Fatalf("signing: %v", err)
	}

	parts := strings.Split(token, ".")
	if len(parts) != 3 {
		t.Fatalf("the token has %d parts, want three", len(parts))
	}

	// The signature verifies over header.claims, which is what a JWT signs.
	digest := sha256.Sum256([]byte(parts[0] + "." + parts[1]))
	signature, err := base64.RawURLEncoding.DecodeString(parts[2])
	if err != nil {
		t.Fatalf("the signature is not base64url: %v", err)
	}
	if err := rsa.VerifyPKCS1v15(&key.PublicKey, crypto.SHA256, digest[:], signature); err != nil {
		t.Fatalf("the signature does not verify: %v", err)
	}

	// And a token signed by a different key must not verify, or the check
	// above proves nothing.
	other, _, _ := throwawayKey(t, MinimumKeyBits)
	if err := rsa.VerifyPKCS1v15(&other.PublicKey, crypto.SHA256, digest[:], signature); err == nil {
		t.Error("the signature verified against an unrelated key")
	}
}

// TestTheTokenHasTheHeaderAndClaimsZellosPortalIssues.
//
// Read from a token Zello's own portal produced: header `{"typ":"JWT",
// "alg":"RS256"}` and claims `iss`, `exp`, `azp`. A claim Zello does not
// expect, or one missing, is a logon refused for a reason that reads like bad
// credentials.
func TestTheTokenHasTheHeaderAndClaimsZellosPortalIssues(t *testing.T) {
	_, pkcs8, _ := throwawayKey(t, MinimumKeyBits)
	fixed := time.Date(2026, 9, 15, 12, 0, 0, 0, time.UTC)

	signer, err := NewSigner(SignerOptions{
		Issuer:        testIssuer,
		PrivateKeyPEM: pkcs8,
		Now:           func() time.Time { return fixed },
	})
	if err != nil {
		t.Fatalf("building a signer: %v", err)
	}
	token, err := signer.Token()
	if err != nil {
		t.Fatalf("signing: %v", err)
	}
	parts := strings.Split(token, ".")

	var header map[string]string
	if err := decodeSegment(t, parts[0], &header); err != nil {
		t.Fatalf("the header: %v", err)
	}
	if header["typ"] != "JWT" || header["alg"] != "RS256" {
		t.Errorf("the header is %v, want typ JWT and alg RS256", header)
	}
	if len(header) != 2 {
		t.Errorf("the header carries %d fields: %v", len(header), header)
	}

	var claims map[string]any
	if err := decodeSegment(t, parts[1], &claims); err != nil {
		t.Fatalf("the claims: %v", err)
	}
	if claims["iss"] != testIssuer {
		t.Errorf("the issuer claim is %v", claims["iss"])
	}
	if claims["azp"] != TokenAudience {
		t.Errorf("the azp claim is %v, want %q", claims["azp"], TokenAudience)
	}
	exp, ok := claims["exp"].(float64)
	if !ok {
		t.Fatalf("the exp claim is %T, want a number", claims["exp"])
	}
	if want := fixed.Add(TokenLifetime).Unix(); int64(exp) != want {
		t.Errorf("the token expires at %d, want %d", int64(exp), want)
	}
	// **In the future, which is the point.** An expiry in the past is a
	// credential that has already stopped working.
	if int64(exp) <= fixed.Unix() {
		t.Error("the token expires before it was made")
	}
	if len(claims) != 3 {
		t.Errorf("the claims carry %d fields: %v", len(claims), claims)
	}
}

// decodeSegment reads one base64url segment of a token.
func decodeSegment(t *testing.T, seg string, into any) error {
	t.Helper()
	// **Unpadded**, which is what a JWT requires: standard base64's padding is
	// rejected by strict parsers, so if this decode needs padding added the
	// token is wrong.
	raw, err := base64.RawURLEncoding.DecodeString(seg)
	if err != nil {
		return err
	}
	return json.Unmarshal(raw, into)
}

// TestTheSegmentsAreBase64urlWithoutPadding.
//
// Standard base64's `+`, `/` and `=` are not safe in a token that travels in
// headers, and a padded segment is rejected by strict parsers. A token that
// works against a lenient server and fails against a strict one is the worst
// kind of intermittent.
func TestTheSegmentsAreBase64urlWithoutPadding(t *testing.T) {
	_, pkcs8, _ := throwawayKey(t, MinimumKeyBits)
	signer, err := NewSigner(SignerOptions{Issuer: testIssuer, PrivateKeyPEM: pkcs8})
	if err != nil {
		t.Fatalf("building a signer: %v", err)
	}

	// Several tokens, because whether a segment would need padding depends on
	// its length and the signature's length varies.
	for i := 0; i < 8; i++ {
		token, err := signer.Token()
		if err != nil {
			t.Fatalf("signing: %v", err)
		}
		for _, bad := range []string{"=", "+", "/"} {
			if strings.Contains(token, bad) {
				t.Errorf("the token contains %q, which base64url does not use: %s",
					bad, token)
			}
		}
		if strings.Count(token, ".") != 2 {
			t.Errorf("the token has %d separators", strings.Count(token, "."))
		}
	}
}

// TestBothPemEncodingsAreAccepted.
//
// `BEGIN PRIVATE KEY` and `BEGIN RSA PRIVATE KEY` look almost identical, and
// an operator pasting whichever their tool produced should not have to know
// which they have.
func TestBothPemEncodingsAreAccepted(t *testing.T) {
	_, pkcs8, pkcs1 := throwawayKey(t, MinimumKeyBits)

	for name, text := range map[string]string{"PKCS#8": pkcs8, "PKCS#1": pkcs1} {
		signer, err := NewSigner(SignerOptions{Issuer: testIssuer, PrivateKeyPEM: text})
		if err != nil {
			t.Errorf("%s was refused: %v", name, err)
			continue
		}
		if _, err := signer.Token(); err != nil {
			t.Errorf("%s signed nothing: %v", name, err)
		}
	}

	// Surrounding whitespace is normal in a pasted key and must not matter.
	padded := "\n\n  " + pkcs8 + "  \n"
	if _, err := NewSigner(SignerOptions{Issuer: testIssuer, PrivateKeyPEM: padded}); err != nil {
		t.Errorf("a key with surrounding whitespace was refused: %v", err)
	}
}

// TestAKeyWithAFourDashHeaderSaysWhatIsWrong.
//
// A PEM header is five dashes each side, and a copy that lost one is
// unreadable everywhere while looking entirely normal. **The operator's own
// first paste had exactly this**, so the message names it rather than saying
// only that the key is unreadable.
func TestAKeyWithAFourDashHeaderSaysWhatIsWrong(t *testing.T) {
	_, pkcs8, _ := throwawayKey(t, MinimumKeyBits)
	damaged := strings.Replace(pkcs8, "-----BEGIN", "----BEGIN", 1)

	_, err := NewSigner(SignerOptions{Issuer: testIssuer, PrivateKeyPEM: damaged})
	if err == nil {
		t.Fatal("a key with a four-dash header was accepted")
	}
	if !strings.Contains(err.Error(), "four dashes") {
		t.Errorf("the message does not name the most likely cause: %v", err)
	}
	if !strings.Contains(err.Error(), "copied") {
		t.Errorf("the message does not say it was probably a copy: %v", err)
	}
}

// TestWhatCannotSignIsRefusedAtStartup.
//
// **A key that cannot be read is a configuration error**, and it should be
// reported when it is entered rather than at the first reconnection at two in
// the morning.
func TestWhatCannotSignIsRefusedAtStartup(t *testing.T) {
	_, pkcs8, _ := throwawayKey(t, MinimumKeyBits)

	// A key too small to be anything but a mistake.
	_, small, _ := throwawayKey(t, 1024)

	// An EC key: valid PEM, valid PKCS#8, and not something RS256 can use.
	ecPEM := ecKeyPEM(t)

	for name, opts := range map[string]SignerOptions{
		"no issuer":       {PrivateKeyPEM: pkcs8},
		"a blank issuer":  {Issuer: "   ", PrivateKeyPEM: pkcs8},
		"no key":          {Issuer: testIssuer},
		"a blank key":     {Issuer: testIssuer, PrivateKeyPEM: "   "},
		"not PEM at all":  {Issuer: testIssuer, PrivateKeyPEM: "hello"},
		"a 1024-bit key":  {Issuer: testIssuer, PrivateKeyPEM: small},
		"an elliptic key": {Issuer: testIssuer, PrivateKeyPEM: ecPEM},
		"the public half": {Issuer: testIssuer, PrivateKeyPEM: publicKeyPEM(t)},
	} {
		if _, err := NewSigner(opts); err == nil {
			t.Errorf("%s was accepted", name)
		}
	}

	// And the message for a short key says why, because 1024 bits looks like
	// a key rather than a mistake.
	if _, err := NewSigner(SignerOptions{Issuer: testIssuer, PrivateKeyPEM: small}); err != nil {
		if !strings.Contains(err.Error(), "pasted by mistake") {
			t.Errorf("the short-key message does not say what it probably is: %v", err)
		}
	}
}

// ecKeyPEM returns an elliptic-curve private key: valid PEM, valid PKCS#8,
// and not something RS256 can use.
func ecKeyPEM(t *testing.T) string {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("generating an EC key: %v", err)
	}
	der, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		t.Fatalf("marshalling an EC key: %v", err)
	}
	return string(pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der}))
}

// publicKeyPEM returns a public key, which an operator can paste by mistake
// because the two blocks look alike.
func publicKeyPEM(t *testing.T) string {
	t.Helper()
	key, err := rsa.GenerateKey(rand.Reader, MinimumKeyBits)
	if err != nil {
		t.Fatalf("generating a key: %v", err)
	}
	der, err := x509.MarshalPKIXPublicKey(&key.PublicKey)
	if err != nil {
		t.Fatalf("marshalling a public key: %v", err)
	}
	return string(pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der}))
}

// TestTheIssuerIsLoggableAndTheKeyIsNot.
//
// An issuer identifies a key pair and is safe in a log; the key is the
// credential. A signer exposing the key would make it one field away from
// every log line.
func TestTheIssuerIsLoggableAndTheKeyIsNot(t *testing.T) {
	_, pkcs8, _ := throwawayKey(t, MinimumKeyBits)
	signer, err := NewSigner(SignerOptions{Issuer: "  " + testIssuer + "  ", PrivateKeyPEM: pkcs8})
	if err != nil {
		t.Fatalf("building a signer: %v", err)
	}
	if got := signer.Issuer(); got != testIssuer {
		t.Errorf("the issuer reads %q; surrounding whitespace should be trimmed", got)
	}

	// The exported surface is the issuer and a token, and nothing that hands
	// back the key.
	token, err := signer.Token()
	if err != nil {
		t.Fatalf("signing: %v", err)
	}
	if strings.Contains(token, "PRIVATE KEY") {
		t.Error("the token carries the key")
	}
}

// TestTokenLifetimeIsShortAndInTheFuture.
//
// A stored token from the portal expires a month out, which is a credential
// that silently stops working on a date nothing records. QSP mints its own per
// connection instead, so the lifetime only has to outlast a handshake.
func TestTokenLifetimeIsShortAndInTheFuture(t *testing.T) {
	if TokenLifetime <= 0 {
		t.Fatalf("the token lifetime is %s", TokenLifetime)
	}
	if TokenLifetime > 24*time.Hour {
		t.Errorf("the token lifetime is %s; a token is minted per connection and "+
			"has nothing to gain from outliving the session", TokenLifetime)
	}
	if TokenLifetime < time.Minute {
		t.Errorf("the token lifetime is %s; a slow handshake or a clock slightly "+
			"out of step would refuse a valid login", TokenLifetime)
	}
}
