package dmrfec

import "fmt"

// # The Link Control checksum, and why this one is from a standard
//
// Everything else in this package was measured from captured traffic, because
// IP Site Connect has no published specification and ADR-0029 forbids inventing
// one. **The DMR air interface is different: it is ETSI TS 102 361-1, a free
// download, and the burst a hotspot expects is specified rather than guessed.**
// The two sides of this bridge therefore get different evidence standards, and
// that distinction is deliberate. See ADR-0040.
//
// The Link Control carried by a voice header or a terminator is nine octets
// protected by a shortened Reed-Solomon (12,9,4) code over GF(2^8), from the
// (255,252,4) code with the first 243 message symbols set to zero (B.3.7). The
// field is generated by alpha^8 + alpha^4 + alpha^3 + alpha^2 + 1 and the code
// by G(x) = (x + alpha)(x + alpha^2)(x + alpha^3).
//
// The three parity octets are computed from the generator matrix of Table B.18
// rather than by polynomial division. That is the spec's own second formulation
// (c = m x G), it is nine multiply-accumulates with no division at all, and it
// is the form that removes an entire class of mistake: an earlier attempt here
// searched thirty thousand candidate divisions and scored zero on every one,
// because the division itself was wrong rather than any of the parameters.
//
// **The masks were not taken from the standard.** They fall out of the
// arithmetic: computing the parity of the 28 real bursts in testdata/hbp/ and
// subtracting what each burst carries leaves 0x969696 on all fourteen voice
// headers and 0x999999 on all fourteen terminators. A wrong construction would
// leave 28 unrelated values.

// rsPrimitive is alpha^8 + alpha^4 + alpha^3 + alpha^2 + 1, ETSI B.3.7 (15).
const rsPrimitive = 0x11D

var rsExp [512]byte
var rsLog [256]byte

func init() {
	x := 1
	for i := 0; i < 255; i++ {
		rsExp[i] = byte(x)
		rsLog[byte(x)] = byte(i)
		x <<= 1
		if x&0x100 != 0 {
			x ^= rsPrimitive
		}
	}
	// Doubling the table lets multiplication add exponents without a modulus.
	for i := 255; i < 512; i++ {
		rsExp[i] = rsExp[i-255]
	}
}

func gfMul(a, b byte) byte {
	if a == 0 || b == 0 {
		return 0
	}
	return rsExp[int(rsLog[a])+int(rsLog[b])]
}

// rsParityColumns is the parity part of the generator matrix, Table B.18: the
// last three columns of each of the nine rows. The identity part is omitted
// because a systematic code copies the message through unchanged.
var rsParityColumns = [LinkControlBytes][3]byte{
	{0x1C, 0xBC, 0xFD},
	{0x89, 0x31, 0x08},
	{0xAD, 0x41, 0x36},
	{0x7D, 0x71, 0x16},
	{0xF3, 0xA6, 0x3A},
	{0x08, 0x83, 0x7B},
	{0x3F, 0x6F, 0x02},
	{0x6C, 0x0D, 0xA7},
	{0x0E, 0x38, 0x40},
}

// LinkControlBytes is the length of a Full Link Control PDU.
const LinkControlBytes = 9

// Data Type values, ETSI Table 9.22. Only the ones this package builds are
// named; naming the rest would suggest QSP produces them.
const (
	// DataTypeVoiceLCHeader opens a voice transmission.
	DataTypeVoiceLCHeader uint8 = 0x1
	// DataTypeTerminatorWithLC closes one.
	DataTypeTerminatorWithLC uint8 = 0x2
	// DataTypeRate34 is a Rate 3/4 coded data block, which is what the
	// content of a text message travels in. It is the one data type whose
	// burst this package codes with a trellis rather than BPTC.
	DataTypeRate34 uint8 = 0x8
)

// rsMaskFor returns the mask applied to the parity for a data type.
//
// Derived from the captures rather than read from a table: see the package
// note above.
func rsMaskFor(dataType uint8) ([3]byte, bool) {
	switch dataType {
	case DataTypeVoiceLCHeader:
		return [3]byte{0x96, 0x96, 0x96}, true
	case DataTypeTerminatorWithLC:
		return [3]byte{0x99, 0x99, 0x99}, true
	default:
		return [3]byte{}, false
	}
}

// RSParity returns the three unmasked Reed-Solomon parity octets for a Link
// Control.
func RSParity(lc []byte) ([3]byte, error) {
	if len(lc) != LinkControlBytes {
		return [3]byte{}, fmt.Errorf("dmrfec: a Link Control is %d octets, got %d",
			LinkControlBytes, len(lc))
	}
	var p [3]byte
	for i := 0; i < LinkControlBytes; i++ {
		for j := 0; j < 3; j++ {
			p[j] ^= gfMul(lc[i], rsParityColumns[i][j])
		}
	}
	return p, nil
}

// LinkControlBlockBytes is the length of the block LinkControlBlock returns:
// nine octets of Link Control and three of masked Reed-Solomon parity.
const LinkControlBlockBytes = LinkControlBytes + 3

// LinkControlBlock builds the twelve octets that carry a Link Control: the nine
// octets themselves followed by the three parity octets, masked for the data
// type.
//
// # Why this is exported separately from LinkControlPayload
//
// These same twelve octets appear in two places, and until IPSC transmit was
// built only one of them was needed. On the air they are the 96-bit
// information block of a BPTC(196,96) data burst, which is what
// LinkControlPayload spreads into bits. Over IPSC they appear as twelve plain
// octets inside a voice header or terminator, because Motorola sends the block
// already decoded and lets the receiving repeater re-encode it.
//
// **That the two are the same twelve octets was measured, not assumed.** Five
// captured headers and terminators from two repeater models, on two different
// talkgroups, reproduce byte for byte: bytes 38 to 49 of a 54-byte IPSC header
// equal this block with the voice-header mask, and the same bytes of a
// terminator equal it with the terminator mask.
func LinkControlBlock(lc []byte, dataType uint8) ([]byte, error) {
	parity, err := RSParity(lc)
	if err != nil {
		return nil, err
	}
	mask, ok := rsMaskFor(dataType)
	if !ok {
		return nil, fmt.Errorf("dmrfec: data type %#x has no Link Control mask; "+
			"this package builds voice headers and terminators only", dataType)
	}
	full := make([]byte, 0, LinkControlBlockBytes)
	full = append(full, lc...)
	for j := 0; j < 3; j++ {
		full = append(full, parity[j]^mask[j])
	}
	return full, nil
}

// LinkControlPayload builds the 96 bits a data burst carries: the Link Control
// followed by its masked checksum, ready for EncodeBPTC.
func LinkControlPayload(lc []byte, dataType uint8) ([]byte, error) {
	full, err := LinkControlBlock(lc, dataType)
	if err != nil {
		return nil, err
	}

	out := make([]byte, BPTCPayloadBits)
	for i, b := range full {
		for bit := 0; bit < 8; bit++ {
			if b&(0x80>>bit) != 0 {
				out[i*8+bit] = 1
			}
		}
	}
	return out, nil
}

// CheckLinkControl reads a Link Control back out of a decoded BPTC payload and
// reports whether its checksum verifies for the given data type.
//
// It exists so the round trip can be asserted rather than assumed, and so a
// caller decoding a captured burst can tell a voice header from a terminator by
// which mask verifies.
func CheckLinkControl(payload []byte, dataType uint8) (lc []byte, ok bool) {
	if len(payload) != BPTCPayloadBits {
		return nil, false
	}
	full := make([]byte, (LinkControlBytes + 3))
	for i := range full {
		for bit := 0; bit < 8; bit++ {
			if payload[i*8+bit] != 0 {
				full[i] |= 0x80 >> bit
			}
		}
	}
	lc = full[:LinkControlBytes]
	want, err := LinkControlPayload(lc, dataType)
	if err != nil {
		return nil, false
	}
	for i := range want {
		if want[i] != payload[i] {
			return nil, false
		}
	}
	return lc, true
}

// # The Slot Type
//
// A general data burst carries twenty bits split either side of the
// synchronisation field: a colour code, a data type, and twelve parity bits
// from a shortened Golay (20,8,7) code (Table 9.4, B.3.1). A receiver reads it
// to know what the burst is, so a wrong one is a burst that is ignored.

// golay208Rows is the parity part of the Golay (20,8) generator matrix,
// Table B.11: twelve parity bits for each of the eight information bits.
var golay208Rows = [8]uint16{
	0b001111011010,
	0b110110011001,
	0b011011001101,
	0b001101100111,
	0b110111000110,
	0b101010100111,
	0b100100111110,
	0b100011101011,
}

// SlotTypeInfo packs a colour code and a DMR data type into the octet that
// carries them together: the colour code in the high nibble, the data type in
// the low.
//
// # Why this is separate from SlotType
//
// On the air the field is twenty bits — these eight and twelve of Golay parity,
// which SlotType builds. **IP Site Connect carries only these eight**, at byte
// 51 of a voice header, a terminator and a text burst, with no parity at all.
//
// It exists because that packing was written inline in two places in the IPSC
// encoder while SlotType computed the same nibbles a third time. A field that is
// two shifts is a field whose nibbles can be swapped without anything looking
// wrong, and ADR-0045's finding that byte 51 agrees with the frame's own data
// type in 153 of 162 captured frames only means something while one expression
// produces both.
func SlotTypeInfo(colourCode, dataType uint8) uint8 {
	return colourCode<<4 | dataType&0x0f
}

// SlotType builds the twenty-bit Slot Type field for a data burst.
func SlotType(colourCode, dataType uint8) (uint32, error) {
	if colourCode > 15 {
		return 0, fmt.Errorf("dmrfec: colour code %d is out of range; DMR allows 0 to 15",
			colourCode)
	}
	if dataType > 15 {
		return 0, fmt.Errorf("dmrfec: data type %#x does not fit in four bits", dataType)
	}
	info := uint16(SlotTypeInfo(colourCode, dataType))
	var parity uint16
	for i := 0; i < 8; i++ {
		if info&(0x80>>i) != 0 {
			parity ^= golay208Rows[i]
		}
	}
	return uint32(info)<<12 | uint32(parity), nil
}

// SlotTypeOf reads the Slot Type back out of a burst, without correction.
func SlotTypeOf(burst []byte) (colourCode, dataType uint8, ok bool) {
	if len(burst) != BurstBytes {
		return 0, 0, false
	}
	b := BurstBitsFrom(burst)
	var v uint32
	for i := 0; i < 10; i++ {
		v = v<<1 | uint32(b[98+i])
	}
	for i := 0; i < 10; i++ {
		v = v<<1 | uint32(b[156+i])
	}
	return uint8(v >> 16 & 0x0F), uint8(v >> 12 & 0x0F), true
}

// DataSyncBS is the synchronisation pattern a base station puts in a general
// data burst, ETSI Table 9.2.
//
// It is what tells a receiver the burst is data rather than voice, and clause
// 5.1.2.3 makes it the thing that actually terminates a voice transmission.
const DataSyncBS = 0xDFF57D75DF5D

// BuildDataBurst produces a complete 33-byte voice header or terminator.
//
// Unlike AssembleDataBurst it needs no template: the Slot Type and the
// synchronisation field are built rather than copied, which is what lets QSP
// open and close a transmission it did not receive one of.
func BuildDataBurst(colourCode, dataType uint8, lc []byte) ([]byte, error) {
	payload, err := LinkControlPayload(lc, dataType)
	if err != nil {
		return nil, err
	}
	return dataBurstFromPayload(colourCode, dataType, payload)
}

// BuildDataBurstFromBlock builds a data burst from a 96-bit information block
// that is already assembled.
//
// # Why this exists beside BuildDataBurst
//
// BuildDataBurst takes a Link Control and computes its Reed-Solomon parity and
// mask on the way. A text message burst arrives from IP Site Connect with its
// twelve octets **already formed** — a CSBK, a data header, or a block of
// user data — and QSP does not know what is inside them, by design: ADR-0037
// settles that a bridge carries a payload and rebuilds the wrapper around it.
//
// Passing those twelve octets through LinkControlPayload would compute parity
// over bytes that are not a Link Control and overwrite two of them with it.
// This is the same assembly with that step left out.
func BuildDataBurstFromBlock(colourCode, dataType uint8, block []byte) ([]byte, error) {
	if len(block) != LinkControlBlockBytes {
		return nil, fmt.Errorf("dmrfec: an information block is %d octets, want %d",
			len(block), LinkControlBlockBytes)
	}
	return dataBurstFromPayload(colourCode, dataType, BurstBitsFrom(block))
}

// dataBurstFromPayload lays 196 coded bits, the Slot Type and the sync pattern
// into one 33-byte burst.
func dataBurstFromPayload(colourCode, dataType uint8, payload []byte) ([]byte, error) {
	coded, err := EncodeBPTC(payload)
	if err != nil {
		return nil, err
	}
	return dataBurstFromCoded(colourCode, dataType, coded)
}

// dataBurstFromCoded lays 196 already-coded bits, the Slot Type and the sync
// pattern into one 33-byte burst.
//
// It is separate from dataBurstFromPayload because a Rate 3/4 block is coded
// with a trellis rather than BPTC, and everything after that coding step —
// where the two 98-bit halves go, where the twenty Slot Type bits go, which
// sync pattern sits between them — is identical for both.
func dataBurstFromCoded(colourCode, dataType uint8, coded []byte) ([]byte, error) {
	if len(coded) != BPTCCodedBits {
		return nil, fmt.Errorf("dmrfec: a coded burst payload is %d bits, want %d",
			len(coded), BPTCCodedBits)
	}
	slot, err := SlotType(colourCode, dataType)
	if err != nil {
		return nil, err
	}

	b := make([]byte, BurstBits)
	copy(b[0:98], coded[0:98])
	copy(b[166:264], coded[98:196])
	// The twenty Slot Type bits sit either side of the 48-bit sync field.
	for i := 0; i < 10; i++ {
		b[98+i] = byte(slot >> (19 - i) & 1)
		b[156+i] = byte(slot >> (9 - i) & 1)
	}
	for i := 0; i < 48; i++ {
		b[108+i] = byte(uint64(DataSyncBS) >> (47 - i) & 1)
	}
	return BurstBytesFrom(b), nil
}

// Full Link Control opcodes, from ETSI TS 102 361-2 and confirmed on air.
//
// **Both were captured.** testdata/ipsc/ipsc-private-voice.pcap carries group
// and private transmissions from two repeater models, and byte 38 of every
// header and terminator reads 0x00 on the group ones and 0x03 on the private
// ones, agreeing with the IPSC leading byte in all 32 frames.
const (
	// FLCOGroupVoice is Grp_V_Ch_Usr, a call to a talkgroup.
	FLCOGroupVoice byte = 0x00
	// FLCOPrivateVoice is UU_V_Ch_Usr, a call to one radio.
	FLCOPrivateVoice byte = 0x03
)

// LinkControlFor builds a Link Control for a transmission.
//
// **The call type is a parameter and not a default.** It was fixed at
// Grp_V_Ch_Usr for as long as this bridge produced only group calls, and a
// private call carrying a group Link Control would tell every receiving radio
// that a conversation between two members is a talkgroup they may join. Making
// the caller say which it is means a new call path cannot inherit the wrong
// answer by saying nothing.
//
// The feature set ID and service options are zero: QSP adds no manufacturer
// features and requests none.
func LinkControlFor(destination, source uint32, private bool) []byte {
	flco := FLCOGroupVoice
	if private {
		flco = FLCOPrivateVoice
	}
	return []byte{
		flco,
		0x00, // FID: standard
		0x00, // service options
		byte(destination >> 16), byte(destination >> 8), byte(destination),
		byte(source >> 16), byte(source >> 8), byte(source),
	}
}
